# Generated by Django 5.0.6 on 2024-07-08 09:22

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_tag_singer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path),
        ),
    ]
