# Generated by Django 5.0.6 on 2024-07-08 10:03

import django.db.models.deletion
import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_singer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='image',
        ),
        migrations.CreateModel(
            name='SingerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=singer.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='singer.singer')),
            ],
        ),
    ]
