# Generated by Django 5.0.6 on 2024-07-08 10:14

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0004_remove_singer_image_singerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path),
        ),
        migrations.DeleteModel(
            name='SingerImage',
        ),
    ]
